### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [aliyigitbireroglu/flutter-snap#1]
Please continue the cleanup and maturation of the project then you can send a PR to join 
https://github.com/Solido/awesome-flutter

**Comment by aliyigitbireroglu** [comment]
Thank you very much, I appreciate. I am at the moment solidifying few things for my [Peek & Pop package](https://github.com/aliyigitbireroglu/flutter-peek-and-pop). I will return to this project over the weekend.

**Comment by Solido** [comment]
Have a look at this for Peek & Pop : 
https://twitter.com/BlueAquilae/status/1160623417483255808
I should have know it before but it was fun !

**Comment by aliyigitbireroglu** [comment]
Seems very cool! I never thought of using ForceTouch like this- I am inspired, thank you 😃
