### ISSUE TITLE
Calendar use case

### ISSUE THREAD

**Issue by joeblew99** [aliyigitbireroglu/flutter-snap#2]
This is a cool library. Congrats.

I immediately thought of making a calendar widget where you can drag the calendar events to different times.
Same as how Google calendar works basically.

Do you think this is appropriate ?

**Comment by aliyigitbireroglu** [comment]
I think it can work. The only thing that comes to my mind: In the case of a calendar, as events for a day/time stack, the "SnapTarget"s will change. So the only important detail is to code the app in such a way that the "SnapTarget"s for one event are dynamically calculated based on the number of stacked events on a certain day/time. Does that make sense?

**Comment by joeblew99** [comment]
thanks for the tips. I will give it a go and let you know how it goes.
