### ISSUE TITLE
Snap only when close to center

### ISSUE THREAD

**Issue by night-wielder** [aliyigitbireroglu/flutter-snap#3]
Hello! THIS IS AN AMAZING LIBRARY, THANK YOU SO MUCH!
I want something like this:
1. Snap to the sides when close to them.
2. Snap to the center when close to it.
3. If both are far, DON'T SNAP.
I can do the former two things. But how do I accomplish the third thing?
Thanks!

**Comment by aliyigitbireroglu** [comment]
Hello! You are very welcome and I am glad to hear that😃

That is a very good suggestion. At the moment, it would be unnecessarily difficult and messy to do so but I believe it is very easy to implement to the library. I will push a new update in the next 1-2 days specifically for this👍🏻

**Comment by night-wielder** [comment]
That would be awesome! Thank you so much!

**Comment by aliyigitbireroglu** [comment]
Hi again. The new update introduces

`minSnapDistance`

and as explained: Use this value to set the minimum distance in pixels required for the snapping to occur. If no [SnapTarget] is found that is closer to the [uiChild] than this value, the snapping will not occur.

I hope this will solve your issue👍🏻
