### ISSUE TITLE
Problem when using Hero

### ISSUE THREAD

**Issue by DennisKragekjaer** [aliyigitbireroglu/flutter-snap#4]
When I try to use the with a Hero widget I get following error:

'package:flutter/src/rendering/object.dart': Failed assertion: line 2293 pos 14: 'renderer != null': is not true.
I suspect it has something to do with the Global Keys.

Do you know how to handle this issue?

**Comment by aliyigitbireroglu** [comment]
Could you share the related code please?

**Comment by DennisKragekjaer** [comment]
When in Hero widget, you set
transitionOnUserGestures: true, then you will see the error/crash.
Maybe it is Hero related

**Comment by DennisKragekjaer** [comment]
Somewhere along the way I did make a mistake.
