### ISSUE TITLE
Null-Safety Support

### ISSUE THREAD

**Issue by nizwar** [aliyigitbireroglu/flutter-snap#7]
Hi, i really love your plugins, and its working like what i expected,

Btw, Do you have any chances to make it support for latest flutter sdk with Nullsafety? it must be amazing :)

**Comment by aliyigitbireroglu** [comment]
Hi! Thank you very much, I am glad you are enjoying the plugins.

Yes, as a matter of fact I will be upgrading all my plugins with null safety this week. It might have to be in the weekend but it will be this week :D

**Comment by nizwar** [comment]
Great!, can't wait for it :)

**Comment by aliyigitbireroglu** [comment]
The package was updated to support null safety. Enjoy!
